export const mockWeather = {
  location: {
    name: "Buenos Aires",
    region: "Distrito Federal",
    country: "Argentina",
    lat: -34.59,
    lon: -58.67,
    tz_id: "America/Argentina/Buenos_Aires",
    localtime_epoch: 1725050410,
    localtime: "2024-08-30 17:40",
    url: "buenos-aires-distrito-federal-argentina",
  },
  current: {
    last_updated_epoch: 1725049800,
    last_updated: "2024-08-30 17:30",
    temp_c: 11.2,
    temp_f: 52.2,
    is_day: 1,
    condition: {
      text: "Moderate or heavy rain with thunder",
      icon: "//cdn.weatherapi.com/weather/64x64/day/389.png",
      code: 1276,
    },
    wind_mph: 12.5,
    wind_kph: 20.2,
    wind_degree: 110,
    wind_dir: "ESE",
    pressure_mb: 1023.0,
    pressure_in: 30.21,
    precip_mm: 2.34,
    precip_in: 0.09,
    humidity: 100,
    cloud: 100,
    feelslike_c: 8.5,
    feelslike_f: 47.2,
    windchill_c: 7.3,
    windchill_f: 45.2,
    heatindex_c: 10.3,
    heatindex_f: 50.5,
    dewpoint_c: 9.8,
    dewpoint_f: 49.6,
    vis_km: 3.0,
    vis_miles: 1.0,
    uv: 4.0,
    gust_mph: 23.1,
    gust_kph: 37.1,
  },
};

export const mockForecast = {
  forecast: {
    forecastday: [
      {
        date: "2024-08-31",
        date_epoch: 1725062400,
        day: {
          maxtemp_c: 11.0,
          maxtemp_f: 51.8,
          mintemp_c: 8.9,
          mintemp_f: 48.0,
          avgtemp_c: 9.8,
          avgtemp_f: 49.7,
          maxwind_mph: 18.8,
          maxwind_kph: 30.2,
          totalprecip_mm: 32.71,
          totalprecip_in: 1.29,
          totalsnow_cm: 0.0,
          avgvis_km: 5.1,
          avgvis_miles: 3.0,
          avghumidity: 96,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 99,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Heavy rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
            code: 1195,
          },
          uv: 1.0,
        },
        astro: {
          sunrise: "07:14 AM",
          sunset: "06:36 PM",
          moonrise: "06:09 AM",
          moonset: "04:20 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: 9,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1725073200,
            time: "2024-08-31 00:00",
            temp_c: 9.3,
            temp_f: 48.8,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 17.7,
            wind_kph: 28.4,
            wind_degree: 122,
            wind_dir: "ESE",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.52,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 100,
            feelslike_c: 5.8,
            feelslike_f: 42.5,
            windchill_c: 5.8,
            windchill_f: 42.5,
            heatindex_c: 9.3,
            heatindex_f: 48.8,
            dewpoint_c: 8.5,
            dewpoint_f: 47.2,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 26.4,
            gust_kph: 42.5,
            uv: 0,
          },
          {
            time_epoch: 1725076800,
            time: "2024-08-31 01:00",
            temp_c: 9.5,
            temp_f: 49.0,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 18.3,
            wind_kph: 29.5,
            wind_degree: 118,
            wind_dir: "ESE",
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.56,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 100,
            feelslike_c: 5.9,
            feelslike_f: 42.6,
            windchill_c: 5.9,
            windchill_f: 42.6,
            heatindex_c: 9.5,
            heatindex_f: 49.0,
            dewpoint_c: 8.6,
            dewpoint_f: 47.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 27.5,
            gust_kph: 44.3,
            uv: 0,
          },
          {
            time_epoch: 1725080400,
            time: "2024-08-31 02:00",
            temp_c: 9.6,
            temp_f: 49.2,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 18.8,
            wind_kph: 30.2,
            wind_degree: 116,
            wind_dir: "ESE",
            pressure_mb: 1020.0,
            pressure_in: 30.13,
            precip_mm: 0.41,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 94,
            cloud: 100,
            feelslike_c: 6.0,
            feelslike_f: 42.8,
            windchill_c: 6.0,
            windchill_f: 42.8,
            heatindex_c: 9.6,
            heatindex_f: 49.2,
            dewpoint_c: 8.6,
            dewpoint_f: 47.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 28.0,
            gust_kph: 45.1,
            uv: 0,
          },
          {
            time_epoch: 1725084000,
            time: "2024-08-31 03:00",
            temp_c: 9.6,
            temp_f: 49.3,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 17.7,
            wind_kph: 28.4,
            wind_degree: 113,
            wind_dir: "ESE",
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 2.4,
            precip_in: 0.09,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 100,
            feelslike_c: 6.2,
            feelslike_f: 43.1,
            windchill_c: 6.2,
            windchill_f: 43.1,
            heatindex_c: 9.6,
            heatindex_f: 49.3,
            dewpoint_c: 8.8,
            dewpoint_f: 47.8,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 26.3,
            gust_kph: 42.3,
            uv: 0,
          },
          {
            time_epoch: 1725087600,
            time: "2024-08-31 04:00",
            temp_c: 9.7,
            temp_f: 49.5,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 17.4,
            wind_kph: 28.1,
            wind_degree: 109,
            wind_dir: "ESE",
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 1.34,
            precip_in: 0.05,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 100,
            feelslike_c: 6.3,
            feelslike_f: 43.4,
            windchill_c: 6.3,
            windchill_f: 43.4,
            heatindex_c: 9.7,
            heatindex_f: 49.5,
            dewpoint_c: 9.0,
            dewpoint_f: 48.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 26.2,
            gust_kph: 42.2,
            uv: 0,
          },
          {
            time_epoch: 1725091200,
            time: "2024-08-31 05:00",
            temp_c: 9.8,
            temp_f: 49.7,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 15.7,
            wind_kph: 25.2,
            wind_degree: 117,
            wind_dir: "ESE",
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 2.24,
            precip_in: 0.09,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 6.7,
            feelslike_f: 44.1,
            windchill_c: 6.7,
            windchill_f: 44.1,
            heatindex_c: 9.8,
            heatindex_f: 49.7,
            dewpoint_c: 9.2,
            dewpoint_f: 48.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 23.7,
            gust_kph: 38.2,
            uv: 0,
          },
          {
            time_epoch: 1725094800,
            time: "2024-08-31 06:00",
            temp_c: 9.8,
            temp_f: 49.7,
            is_day: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/302.png",
              code: 1189,
            },
            wind_mph: 14.5,
            wind_kph: 23.4,
            wind_degree: 121,
            wind_dir: "ESE",
            pressure_mb: 1018.0,
            pressure_in: 30.06,
            precip_mm: 4.03,
            precip_in: 0.16,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 6.8,
            feelslike_f: 44.3,
            windchill_c: 6.8,
            windchill_f: 44.3,
            heatindex_c: 9.8,
            heatindex_f: 49.7,
            dewpoint_c: 9.3,
            dewpoint_f: 48.7,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7.0,
            vis_miles: 4.0,
            gust_mph: 21.9,
            gust_kph: 35.2,
            uv: 0,
          },
          {
            time_epoch: 1725098400,
            time: "2024-08-31 07:00",
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/302.png",
              code: 1189,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 124,
            wind_dir: "SE",
            pressure_mb: 1018.0,
            pressure_in: 30.06,
            precip_mm: 4.25,
            precip_in: 0.17,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 7.3,
            feelslike_f: 45.1,
            windchill_c: 7.3,
            windchill_f: 45.1,
            heatindex_c: 9.9,
            heatindex_f: 49.8,
            dewpoint_c: 9.4,
            dewpoint_f: 48.8,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7.0,
            vis_miles: 4.0,
            gust_mph: 18.3,
            gust_kph: 29.5,
            uv: 0,
          },
          {
            time_epoch: 1725102000,
            time: "2024-08-31 08:00",
            temp_c: 10.0,
            temp_f: 49.9,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 132,
            wind_dir: "SE",
            pressure_mb: 1018.0,
            pressure_in: 30.06,
            precip_mm: 4.89,
            precip_in: 0.19,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 7.5,
            feelslike_f: 45.6,
            windchill_c: 7.5,
            windchill_f: 45.6,
            heatindex_c: 10.0,
            heatindex_f: 49.9,
            dewpoint_c: 9.5,
            dewpoint_f: 49.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7.0,
            vis_miles: 4.0,
            gust_mph: 16.8,
            gust_kph: 27.1,
            uv: 3.0,
          },
          {
            time_epoch: 1725105600,
            time: "2024-08-31 09:00",
            temp_c: 10.0,
            temp_f: 50.0,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 151,
            wind_dir: "SSE",
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 5.25,
            precip_in: 0.21,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 7.7,
            feelslike_f: 45.9,
            windchill_c: 7.7,
            windchill_f: 45.9,
            heatindex_c: 10.0,
            heatindex_f: 50.0,
            dewpoint_c: 9.6,
            dewpoint_f: 49.2,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7.0,
            vis_miles: 4.0,
            gust_mph: 15.3,
            gust_kph: 24.6,
            uv: 3.0,
          },
          {
            time_epoch: 1725109200,
            time: "2024-08-31 10:00",
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 154,
            wind_dir: "SSE",
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 2.59,
            precip_in: 0.1,
            snow_cm: 0.0,
            humidity: 98,
            cloud: 100,
            feelslike_c: 7.4,
            feelslike_f: 45.3,
            windchill_c: 7.4,
            windchill_f: 45.3,
            heatindex_c: 9.9,
            heatindex_f: 49.8,
            dewpoint_c: 9.6,
            dewpoint_f: 49.2,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7.0,
            vis_miles: 4.0,
            gust_mph: 16.8,
            gust_kph: 27.0,
            uv: 3.0,
          },
          {
            time_epoch: 1725112800,
            time: "2024-08-31 11:00",
            temp_c: 9.9,
            temp_f: 49.9,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 143,
            wind_dir: "SE",
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 2.27,
            precip_in: 0.09,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 7.2,
            feelslike_f: 45.0,
            windchill_c: 7.2,
            windchill_f: 45.0,
            heatindex_c: 10.0,
            heatindex_f: 49.9,
            dewpoint_c: 9.5,
            dewpoint_f: 49.2,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 19.2,
            gust_kph: 30.9,
            uv: 3.0,
          },
          {
            time_epoch: 1725116400,
            time: "2024-08-31 12:00",
            temp_c: 10.2,
            temp_f: 50.4,
            is_day: 1,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
              code: 1153,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 136,
            wind_dir: "SE",
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.42,
            precip_in: 0.02,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 7.6,
            feelslike_f: 45.7,
            windchill_c: 7.6,
            windchill_f: 45.7,
            heatindex_c: 10.2,
            heatindex_f: 50.4,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 18.7,
            gust_kph: 30.2,
            uv: 4.0,
          },
          {
            time_epoch: 1725120000,
            time: "2024-08-31 13:00",
            temp_c: 12.1,
            temp_f: 53.8,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 20.6,
            wind_kph: 33.1,
            wind_degree: 130,
            wind_dir: "SE",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.05,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 100,
            cloud: 100,
            feelslike_c: 8.9,
            feelslike_f: 48.1,
            windchill_c: 8.9,
            windchill_f: 48.1,
            heatindex_c: 11.0,
            heatindex_f: 51.7,
            dewpoint_c: 10.2,
            dewpoint_f: 50.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 25.1,
            gust_kph: 40.3,
            uv: 4.0,
          },
          {
            time_epoch: 1725123600,
            time: "2024-08-31 14:00",
            temp_c: 10.8,
            temp_f: 51.5,
            is_day: 1,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
              code: 1030,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 150,
            wind_dir: "SSE",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.06,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 9.3,
            feelslike_f: 48.8,
            windchill_c: 9.3,
            windchill_f: 48.8,
            heatindex_c: 10.8,
            heatindex_f: 51.5,
            dewpoint_c: 10.2,
            dewpoint_f: 50.3,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 10.6,
            gust_kph: 17.1,
            uv: 4.0,
          },
          {
            time_epoch: 1725127200,
            time: "2024-08-31 15:00",
            temp_c: 10.7,
            temp_f: 51.3,
            is_day: 1,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
              code: 1030,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 186,
            wind_dir: "S",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.08,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 9.7,
            feelslike_f: 49.4,
            windchill_c: 9.7,
            windchill_f: 49.4,
            heatindex_c: 10.7,
            heatindex_f: 51.3,
            dewpoint_c: 10.2,
            dewpoint_f: 50.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
            uv: 4.0,
          },
          {
            time_epoch: 1725130800,
            time: "2024-08-31 16:00",
            temp_c: 10.5,
            temp_f: 50.8,
            is_day: 1,
            condition: {
              text: "Fog",
              icon: "//cdn.weatherapi.com/weather/64x64/day/248.png",
              code: 1135,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 213,
            wind_dir: "SSW",
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.08,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 8.9,
            feelslike_f: 48.0,
            windchill_c: 8.9,
            windchill_f: 48.0,
            heatindex_c: 10.5,
            heatindex_f: 50.8,
            dewpoint_c: 10.0,
            dewpoint_f: 50.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0.0,
            vis_miles: 0.0,
            gust_mph: 10.7,
            gust_kph: 17.2,
            uv: 4.0,
          },
          {
            time_epoch: 1725134400,
            time: "2024-08-31 17:00",
            temp_c: 9.9,
            temp_f: 49.9,
            is_day: 1,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
              code: 1153,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 218,
            wind_dir: "SW",
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.19,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 7.7,
            feelslike_f: 45.9,
            windchill_c: 7.7,
            windchill_f: 45.9,
            heatindex_c: 9.9,
            heatindex_f: 49.9,
            dewpoint_c: 9.5,
            dewpoint_f: 49.2,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 14.2,
            gust_kph: 22.9,
            uv: 3.0,
          },
          {
            time_epoch: 1725138000,
            time: "2024-08-31 18:00",
            temp_c: 9.5,
            temp_f: 49.1,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 213,
            wind_dir: "SSW",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.1,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 7.0,
            feelslike_f: 44.6,
            windchill_c: 7.0,
            windchill_f: 44.6,
            heatindex_c: 9.5,
            heatindex_f: 49.1,
            dewpoint_c: 9.1,
            dewpoint_f: 48.3,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.0,
            gust_kph: 25.7,
            uv: 3.0,
          },
          {
            time_epoch: 1725141600,
            time: "2024-08-31 19:00",
            temp_c: 9.3,
            temp_f: 48.7,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 208,
            wind_dir: "SSW",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.06,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 9.3,
            heatindex_f: 48.7,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.8,
            gust_kph: 27.0,
            uv: 0,
          },
          {
            time_epoch: 1725145200,
            time: "2024-08-31 20:00",
            temp_c: 9.2,
            temp_f: 48.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1016.0,
            pressure_in: 29.99,
            precip_mm: 0.18,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 9.2,
            heatindex_f: 48.6,
            dewpoint_c: 8.7,
            dewpoint_f: 47.6,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 16.3,
            gust_kph: 26.2,
            uv: 0,
          },
          {
            time_epoch: 1725148800,
            time: "2024-08-31 21:00",
            temp_c: 9.2,
            temp_f: 48.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 216,
            wind_dir: "SW",
            pressure_mb: 1016.0,
            pressure_in: 30.01,
            precip_mm: 0.25,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 6.4,
            feelslike_f: 43.6,
            windchill_c: 6.4,
            windchill_f: 43.6,
            heatindex_c: 9.2,
            heatindex_f: 48.6,
            dewpoint_c: 8.7,
            dewpoint_f: 47.6,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 18.0,
            gust_kph: 28.9,
            uv: 0,
          },
          {
            time_epoch: 1725152400,
            time: "2024-08-31 22:00",
            temp_c: 9.1,
            temp_f: 48.3,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.18,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 6.1,
            feelslike_f: 43.0,
            windchill_c: 6.1,
            windchill_f: 43.0,
            heatindex_c: 9.1,
            heatindex_f: 48.3,
            dewpoint_c: 8.5,
            dewpoint_f: 47.2,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 19.3,
            gust_kph: 31.0,
            uv: 0,
          },
          {
            time_epoch: 1725156000,
            time: "2024-08-31 23:00",
            temp_c: 8.9,
            temp_f: 48.0,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 216,
            wind_dir: "SW",
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.32,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 5.8,
            feelslike_f: 42.4,
            windchill_c: 5.8,
            windchill_f: 42.4,
            heatindex_c: 8.9,
            heatindex_f: 48.1,
            dewpoint_c: 8.3,
            dewpoint_f: 47.0,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 20.5,
            gust_kph: 32.9,
            uv: 0,
          },
        ],
      },
    ],
  },
};

export const mockUser = {
  id: "1",
  email: "email@test.com",
  password: "1234",
};
